#+title: Homes as Spaces of Trapped Memories
#+date: <2024-12-22 19:34>
#+description: Or, "How the home as collective entity contains so many trapped spaces of lived experiences"
#+filetags: :memory:emotion:

I have not read "The Poetics of Space". A copy of Bachelard's classic work rests on my table and eyes me menacingly. I know not of his ideas, nor do I have the slightest clue as to how he understands the 'Poetics of Space'. But, a glance around the room that I am seated in, makes me feel that I intimately understand Bachelard, albeit in my own quaint way.

This melancholy surrounding me, is out of the blue and came as a result of a call I received this evening. A close friend had just lost their maternal grandfather, a loss that I myself am closely acquainted with. The spontaneous expression of grief and the tear drops that rolled through their eyes, reminded me of a similar experience I dealt with not long ago. I remember not crying. Possibly because I never felt his loss. Possibly because the shock was so fatal that I could do nothing but exclaim at the events unfolding around me. I have still not fully understood the consequences of his absence. But out of all these reasons, I feel that the primary cause of this behavior, is because I never really felt his loss.

My Nana (as we affectionately called him in Hindi) was a wonderful academic and a brilliant legal practitioner. He had studied Zoology, worked for 25 years in the Revenue Services and finally took up Law. This diverse academic background made him a true renaissance man, and his library reflected his diverse experiences. He stored the wonders of the animal world, the beauty of Hindu Philosophy, the erudite works of legal scholars all within the small confines of the library. During his lifetime, and since then, I have inherited all of these books. I never felt his absence in the presence of these compressed collection of memories. The seeming random annotations he made, guide me in ways I know nothing of. But there is a sense of comfort, knowing that I am still in his watchful guidance. As I walk into a courtroom with books labelled under his initials, I donn his personality, his style of presentation, his style of speaking. There is nothing that I can clearly discribe this feeling. The library is this collection of compressed memories that I have the honor to maintain. He placed me not as the owner of this pool of transcendental knowledge, but as a custodian, a trustee. The library is one of the many places where memories reside permanently, trapped within the confines of each page, waiting for someone to open and experiance them.

The space one occupies creates experiances around that space, which with the passage of time convert into memories. My experiance though is confined to the four corners of piece of paper. A collection of letters I maintain, are the only memory I have of my great grandfather. 
